version: "3.7"

services:
  api:
    build: .
    container_name: api
    command: bash -c "python -m alembic upgrade head && python -m uvicorn --host=0.0.0.0 app.v1.main:api"
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:qwerty123@database:5400/api"
    depends_on:
      - database
    networks:
      - vatusa
  database:
    image: postgres:14
    container_name: database
    environment:
      - PGPORT=5400
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=api
    ports:
      - "5400:5400"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - vatusa
volumes:
  postgres-data: null
networks:
  vatusa: null
