name: Build Image
on:
  pull_request:
    types: [opened, reopened]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Build image
      run: docker build -t api .
